"""Render orchestrator-track tasks for Harbor, or materialise them locally.

Harbor layout (verified against harbor 0.23.0):

    <task>/task.toml          metadata: family, size, delegation label, limits
    <task>/instruction.md     the only thing the agent is told
    <task>/environment/       Dockerfile + workspace/ (+ opt/ for tools)
    <task>/tests/             test.sh, verify.py, ground_truth.json, hidden checks
    <task>/solution/solve.sh  the oracle: `harbor run -a oracle` must score 1.0

The ground truth lives only in tests/, which Harbor uploads after the agent has
finished. That is stricter than HANDOFF's /opt/handoff: nothing the agent can
reach knows the answer.
"""

import json
import shutil
from pathlib import Path

from orch.families import FAMILIES

VERIFY_SRC = Path(__file__).with_name("verify.py")
# Every task is long-horizon (60-150+ solo steps), so every agent gets an hour.
AGENT_TIMEOUT = {"W": 3600, "P": 3600, "C": 3600, "L": 3600}


def _toml_value(value):
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_toml_value(v) for v in value) + "]"
    return json.dumps(str(value))


def task_toml(task):
    meta = {
        "track": "orchestrator",
        "family": task.family,
        "size": task.size,
        "seed": task.seed,
        "delegation_label": task.label,
        "work_items": task.work_items,
    }
    lines = [
        f"# Generated by subagent-bench (orch/emit.py) from {task.id}. Regenerate; don't edit.",
        'schema_version = "1.4"',
        "",
        "[task]",
        f'name = "subagent-bench/{task.id}"',
        f'description = "Orchestrator track, family {task.family}, size {task.size}."',
        'keywords = ["subagent-bench", "orchestrator", "delegation", '
        f'"family-{task.family.lower()}"]',
        "",
        "[metadata]",
    ]
    lines += [f"{k} = {_toml_value(v)}" for k, v in meta.items()]
    lines += ["", "[metadata.limits]"]
    lines += [f"{k} = {_toml_value(v)}" for k, v in task.limits.items()]
    lines += [
        "",
        "[agent]",
        f"timeout_sec = {float(AGENT_TIMEOUT[task.family])}",
        "",
        "[verifier]",
        "timeout_sec = 120.0",
        "",
        "[environment]",
        "cpus = 1",
        "memory_mb = 2048",
        "",
    ]
    return "\n".join(lines)


def dockerfile(task):
    lines = [
        "FROM python:3.12-slim",
        "WORKDIR /workspace",
        "COPY workspace/ /workspace/",
    ]
    if task.tool_files:
        lines.append("COPY opt/ /opt/")
        for path, text in sorted(task.tool_files.items()):
            if text.startswith("#!"):
                name = Path(path).name
                lines.append(f"RUN chmod +x {path} && ln -s {path} /usr/local/bin/{name}")
    for key, value in sorted(task.env.items()):
        lines.append(f"ENV {key}={value}")
    return "\n".join(lines) + "\n"


TEST_SH = """#!/usr/bin/env bash
# Grades /workspace against /tests/ground_truth.json; writes /logs/verifier/reward.json.
set -uo pipefail
mkdir -p /logs/verifier
cd /workspace
python3 /tests/verify.py
"""


def write_workspace(task, root):
    root = Path(root)
    root.mkdir(parents=True, exist_ok=True)
    for rel, text in task.files.items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    if not task.files:
        (root / ".keep").write_text("")
    return root


def write_tools(task, root):
    """Write tool files under `root`, mirroring their absolute image paths."""
    root = Path(root)
    written = {}
    for path, text in task.tool_files.items():
        if not path.startswith("/opt/"):
            raise ValueError(f"tool files must live under /opt: {path}")
        dest = root / path.lstrip("/")
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(text)
        if text.startswith("#!"):
            dest.chmod(0o755)
        written[path] = dest
    return written


def write_tests(task, tests_dir):
    tests_dir = Path(tests_dir)
    tests_dir.mkdir(parents=True, exist_ok=True)
    truth = dict(task.truth, family=task.family, task_id=task.id)
    (tests_dir / "ground_truth.json").write_text(json.dumps(truth, indent=2))
    shutil.copy(VERIFY_SRC, tests_dir / "verify.py")
    for rel, text in task.hidden_tests.items():
        (tests_dir / rel).write_text(text)
    return tests_dir


def emit(task, out_dir):
    out = Path(out_dir)
    if out.exists():
        shutil.rmtree(out)
    (out / "environment").mkdir(parents=True)
    (out / "instruction.md").write_text(task.instruction)
    (out / "task.toml").write_text(task_toml(task))
    write_workspace(task, out / "environment" / "workspace")
    if task.tool_files:
        write_tools(task, out / "environment")
    (out / "environment" / "Dockerfile").write_text(dockerfile(task))
    tests = write_tests(task, out / "tests")
    (tests / "test.sh").write_text(TEST_SH)
    (tests / "test.sh").chmod(0o755)
    (out / "solution").mkdir()
    solve = out / "solution" / "solve.sh"
    solve.write_text("#!/usr/bin/env bash\nset -euo pipefail\ncd /workspace\n" + task.solution)
    solve.chmod(0o755)
    return out


def generate_set(sizes=None, seeds=(1,), families=None):
    """Every (family, size, seed) combination. `sizes` maps family -> sizes."""
    tasks = []
    for name, module in FAMILIES.items():
        if families and name not in families:
            continue
        for size in (sizes or {}).get(name, module.SIZES):
            for seed in seeds:
                tasks.append(module.generate(size, seed))
    return tasks


def emit_set(tasks, out_dir):
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = [emit(task, out_dir / task.id) for task in tasks]
    manifest = [
        {"id": t.id, "family": t.family, "size": t.size, "seed": t.seed, "label": t.label,
         "work_items": t.work_items}
        for t in tasks
    ]
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2))
    (out_dir / "README.md").write_text(dataset_readme(tasks, out_dir.name))
    return written


UNITS = {"W": "support tickets to sweep", "P": "services to diagnose",
         "C": "views to update behind a shared record format", "L": "ledger hops to follow, in order"}


def dataset_readme(tasks, name):
    rows = {}
    for t in tasks:
        rows.setdefault((t.family, t.size, t.label), []).append(t.seed)
    order = {f: i for i, f in enumerate(FAMILIES)}
    table = "\n".join(
        f"| {f} | {n} {UNITS[f]} | `{label}` | {', '.join(map(str, sorted(seeds)))} | "
        f"`orch-{f.lower()}-n{n}-s*` |"
        for (f, n, label), seeds in sorted(rows.items(), key=lambda k: (order[k[0][0]], k[0][1])))
    return f"""# {name}: orchestrator-track task set

{len(tasks)} Harbor tasks. Generated by `tools/orch_generate.py`, and
`tests/test_orch_tasks.py` fails if this directory drifts from the generators,
so regenerate rather than edit. Every task is long-horizon: a scripted agent
with perfect reading and unlimited context needs 60-160 steps
(`tests/test_orch_harness.py` enforces it). See `../../ORCHESTRATOR.md`.

| family | size | delegation label | seeds | task ids |
|---|---|---|---|---|
{table}

`delegate`: the work splits into independent, named units, and a solo agent under
the reference limits (32k context, 160 steps) hits the context wall as size grows.
For C the split only works if the lead fixes the job record format and puts it in
every brief. `solo`: the work is a chain of dependent steps with nothing to run in
parallel.

Each task directory is standard Harbor:

```
task.toml          metadata: family, size, seed, delegation_label, work_items, limits
instruction.md     the only thing the agent is told
environment/       Dockerfile + workspace/ (+ opt/svcctl for P)
tests/             verify.py + ground_truth.json (+ hidden_checks.py for C)
solution/solve.sh  oracle; must score 1.0
```

Run it:

```bash
harbor run -p datasets/{name} -a oracle                                   # sanity: all 1.0
harbor run -p datasets/{name} -a claude-code -m <model> --ak disallowed_tools=Agent,Task -o jobs/solo
harbor run -p datasets/{name} -a claude-code -m <model> -o jobs/delegate
python tools/orch_collect.py jobs/solo jobs/delegate
```

`reward.json` carries `reward` in [0, 1] plus sub-scores. The ground truth is only
in `tests/`, which Harbor uploads after the agent finishes.
"""
