#!/usr/bin/env python3
"""Assemble the long-horizon track's Harbor task directories.

    python tools/build_longhorizon.py            # write longhorizon/tasks/<family>/
    python tools/build_longhorizon.py --check    # fail if a committed task dir is stale

One task per family, each a different job. Each task directory is Harbor's
layout, plus a REQUIREMENTS.md for people:

    task.toml          Harbor schema: org/name, [metadata] (incl. the budget-gate
                       numbers), no network, pinned CPU and memory
    instruction.md     the brief -- all the agent is told
    REQUIREMENTS.md    what the image holds, what completes the task, and why a
                       single agent runs out of time where a delegating one does not
    environment/       Dockerfile + the generator; the generator runs in a BUILD
                       stage only, so the final image holds the workspace and not
                       the code that knows the answers
    tests/test.sh      regenerates the ground truth from the same seed and grades
    solution/solve.sh  the reference solution, for Harbor's oracle agent: a
                       hand-written solver that reads only the workspace where
                       longhorizon/solutions/<family>.py exists, else the
                       generator's answer key

Each family's generator lives once, in longhorizon/generators/, and exposes the
same interface: generate(), grade(), an oracle, shape() for the budget model,
INSTRUCTION and ANSWER_PATH. This tool copies it into environment/, tests/ and
solution/, because a Docker build context cannot reach outside its own
directory. `--check` (and a test) catches drift. A task the budget gate does
not admit is never written.
"""

import argparse
import difflib
import importlib
import json
import math
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "longhorizon"))
sys.path.insert(0, str(ROOT / "longhorizon" / "generators"))

from budget import Assumptions, TaskShape, gate  # noqa: E402

GEN = ROOT / "longhorizon" / "generators"
OUT = ROOT / "longhorizon" / "tasks"
SEED = 1
TIMEOUT_S = 1200
PYTEST = "RUN pip install --no-cache-dir 'pytest>=8,<9'\n"

# One task per family: every task is a different job, not a reseeded copy.
# Generators stay seedable, so a held-out split or a contamination refresh is a
# new seed away (DESIGN.md 7.4), but the committed set has no near-duplicates.
FAMILIES = [
    "lh1_fleet_audit", "lh2_migration_fanout", "lh3_incident_timeline", "lh4_license_review",
    "lh5_config_layering", "lh6_flake_triage", "lh7_i18n_qa", "lh8_plugin_port",
    "lh9_backport", "lh10_column_drop", "lh11_test_authoring", "lh12_issue_fixes", "lh13_sql_reports",
    "lh14_log_parsers", "lh15_perf_fixes", "lh16_shell_port", "lh17_flag_cleanup", "lh18_docker_hardening",
    "lh19_a11y_fixes", "lh20_docs_drift", "lh21_data_cleaning", "lh22_reconciliation", "lh23_experiment_audit",
    "lh24_contract_terms", "lh25_ticket_triage", "lh26_expense_audit", "lh27_secret_leaks", "lh28_iam_access",
    "lh29_fictional_calendars", "lh30_spec_validators", "lh31_assay_replicates",
    # science, mathematics and biology
    "lh32_meta_analysis", "lh33_pedigree_inheritance", "lh34_transit_vetting", "lh35_outbreak_investigation",
    "lh36_reaction_yields", "lh37_proof_grading", "lh38_counting_problems", "lh39_ecology_surveys",
]


def meta(family):
    return family_module(family).META


DOCKERFILE = """\
# syntax=docker/dockerfile:1
# {task_id} -- generated by tools/build_longhorizon.py; edit the generator, not this file.
#
# Stage 1 runs the generator and is thrown away. The final image holds only the
# workspace, never the code that knows the answers.
FROM python:3.12-slim AS build
ARG SEED={seed}
COPY common.py generate.py /gen/
RUN python3 /gen/generate.py --seed "$SEED" --out /fixture

FROM python:3.12-slim
RUN apt-get update \\
 && apt-get install -y --no-install-recommends git ripgrep jq less procps{apt_extra} \\
 && rm -rf /var/lib/apt/lists/*
{extra_packages}COPY --from=build /fixture/workspace /workspace
WORKDIR /workspace
# A baseline commit, so `git diff` shows the agent exactly what it changed.
RUN git init -q && git add -A \\
 && git -c user.email=bench@handoff -c user.name=handoff commit -qm baseline
"""

TEST_SH = """\
#!/usr/bin/env bash
# Harbor verifier. Regenerates the ground truth from the image's seed -- the
# answers were never in the image -- grades, and writes the reward.
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
mkdir -p /logs/verifier
python3 "$HERE/generate.py" --seed {seed} --grade {answer} > /logs/verifier/grade.json
python3 -c "import json; print(json.load(open('/logs/verifier/grade.json'))['reward'])" \\
  > /logs/verifier/reward.txt
cat /logs/verifier/reward.txt
"""

SOLVE_SH = """\
#!/usr/bin/env bash
# Reference solution for Harbor's oracle agent: proves the grader awards full
# marks. It reads the answers from the generator, so it says nothing about
# whether the task can be solved from the workspace alone.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
python3 "$HERE/generate.py" --seed {seed} --solve {answer}
"""

# A family with a hand-written solver in longhorizon/solutions/ ships that
# instead: it reads only /workspace, as an agent would, and never the
# generator, so a full score proves the answers follow from the workspace.
SOLUTIONS = ROOT / "longhorizon" / "solutions"

SOLVE_FROM_WORKSPACE_SH = """\
#!/usr/bin/env bash
# Reference solution for Harbor's oracle agent, written like an agent: it reads
# only /workspace and docs/, never the generator or the answer key. A full score
# proves the task is solvable from what the agent is given.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
python3 "$HERE/solve.py" /workspace
"""

# Harbor task schema (harbor.models.task.config.TaskConfig), laid out as
# DeepSWE's tasks are: org/name, top-level [metadata], no network for agent or
# verifier, and pinned resources, since the timeout argument depends on speed.
HARBOR_SCHEMA_VERSION = "1.4"
ORG = "handoff"
CPUS = 2
MEMORY_MB = 4096
STORAGE_MB = 10240
VERIFIER_TIMEOUT_S = 900

TASK_TOML = """\
# Generated by tools/build_longhorizon.py -- edit the generator, not this file.
schema_version = "{schema_version}"

[task]
name = "{org}/{task_id}"
description = {description}
keywords = ["handoff", "long-horizon", "delegation", "{kind}", "{domain}"]

[metadata]
track = "long-horizon"
family = "{family}"
kind = "{kind}"
domain = "{domain}"
seed = {seed}
units = {units}
unit = "{unit}"
answer_path = "{answer}"
# Budget-gate estimates (longhorizon/budget.py). Latency, decode and output-token
# constants are assumptions until calibrated; unit sizes are measured.
est_single_agent_min = {careful}
est_single_agent_floor_min = {floor}
est_delegated_min = {delegated}
est_total_tokens = {tokens}

[agent]
timeout_sec = {timeout}
network_mode = "no-network"

[verifier]
timeout_sec = {verifier_timeout}
network_mode = "no-network"
environment_mode = "shared"

[environment]
build_timeout_sec = 1200
network_mode = "no-network"
workdir = "/workspace"
cpus = {cpus}
memory_mb = {memory_mb}
storage_mb = {storage_mb}
"""


def description(module):
    """The generator docstring's title line, without its "LHn --" prefix."""
    title = module.__doc__.strip().splitlines()[0]
    title = title.split(" -- ", 1)[-1].rstrip(".")
    return title[:1].upper() + title[1:]


def family_module(family):
    return importlib.import_module(family)


def task_shape(family, seed):
    m = family_module(family)
    s = m.shape(seed)
    return TaskShape(f"{family}_s{seed}", s["unit_chars"], s["judgement_turns"],
                     s["orchestration_turns"], meta(family)["output_tokens"],
                     s.get("shared_chars", 0), TIMEOUT_S)


def requirements_md(task_id, family, seed, cfg, g, a, shape):
    median = sorted(shape.unit_chars)[len(shape.unit_chars) // 2]
    turns = math.ceil(median / 30_000) + shape.judgement_turns
    tools = "`git`, `ripgrep`, `jq` and `less`" + (" and `pytest`" if cfg["extra_packages"] else "")
    lines = [
        f"# {task_id}: what completing it requires",
        "",
        f"Seed {seed}. Probes: {cfg['failure_mode']}.",
        "",
        "## What the agent gets",
        "",
        f"A `python:3.12-slim` container with {tools}, and a generated workspace at `/workspace` "
        "(committed as a git baseline). There is no network access and no model access inside the "
        "container, so the agent cannot parallelise by starting a second copy of itself: only its "
        "harness's own subagents can do that. The generator runs in a throwaway build stage; the "
        "ground truth is never in the final image, and the verifier regenerates it from the seed.",
        "",
        "## What completes the task",
        "",
        f"- Deliverable: {cfg['deliverable']}.",
        f"- Grading: {cfg['grading']}",
        f"- Agent timeout: {g['timeout_min']:.0f} minutes of wall clock (`task.toml`).",
        "",
        "## Why one agent times out and a delegating one does not",
        "",
        f"There are {g['units']} independent {cfg['unit']}s. For each one the agent must "
        f"{cfg['per_unit']}. That is about {turns} turns and {cfg['output_tokens']:,} tokens of "
        f"reasoning and output per {cfg['unit']}.",
        "",
        "| | estimate |",
        "|---|---|",
        f"| single agent, careful (unit by unit) | **{g['single_agent_min']} min** |",
        f"| single agent, ideal (batches every read; floor) | **{g['single_agent_floor_min']} min** "
        f"({g['single_agent_compactions']} compactions) |",
        f"| orchestrator + {a.parallel_subagents} careful subagents in parallel | "
        f"**{g['delegated_min']} min** (peak {g['subagent_peak_tokens']:,} tokens per subagent) |",
        f"| timeout | {g['timeout_min']:.0f} min |",
        "",
        "What even the ideal single agent cannot batch away is the reasoning and output for "
        f"{g['units']} {cfg['unit']}s ({g['output_tokens']:,} tokens, decoded one after another). "
        "Parallel subagents decode theirs at the same time. Subagents run one after another do not "
        "help; the task rewards **parallel** delegation.",
        "",
        f"Gate: {'**admitted**' if g['admitted'] else '**NOT admitted**'} "
        f"({', '.join(f'{k}: {v}' for k, v in g['checks'].items())}). "
        "Unit sizes are measured from the generated workspace; latency, decode speed and output "
        "tokens per unit are assumptions until the calibration run in `longhorizon/README.md`.",
        "",
        "## Traps",
        "",
    ] + [f"- {t}" for t in cfg["traps"]] + [
        "",
        "## Build and verify",
        "",
        "```bash",
        f"docker build -t {task_id} longhorizon/tasks/{task_id}/environment",
        "harbor run -p longhorizon/tasks -a oracle          # the oracle must score 1.0",
        "```",
        "",
    ]
    return "\n".join(lines)


def build(family, seed=SEED, out_root=OUT):
    cfg = dict(meta(family))
    cfg["extra_packages"] = PYTEST if cfg.get("needs_pytest") else ""
    m = family_module(family)
    a = Assumptions()
    shape = task_shape(family, seed)
    g = gate(shape, a)
    task_id = family
    files = {
        "instruction.md": m.INSTRUCTION,
        "task.toml": TASK_TOML.format(schema_version=HARBOR_SCHEMA_VERSION, org=ORG, task_id=task_id,
                                      description=json.dumps(description(m)), kind=cfg["kind"],
                                      domain=cfg["domain"], family=family, seed=seed, units=g["units"],
                                      unit=cfg["unit"], answer=m.ANSWER_PATH, careful=g["single_agent_min"],
                                      floor=g["single_agent_floor_min"], delegated=g["delegated_min"],
                                      tokens=g["total_tokens"], timeout=TIMEOUT_S,
                                      verifier_timeout=VERIFIER_TIMEOUT_S, cpus=CPUS, memory_mb=MEMORY_MB,
                                      storage_mb=STORAGE_MB),
        "REQUIREMENTS.md": requirements_md(task_id, family, seed, cfg, g, a, shape),
        "environment/Dockerfile": DOCKERFILE.format(task_id=task_id, seed=seed,
                                                    extra_packages=cfg["extra_packages"],
                                                    apt_extra="".join(f" {a}" for a in cfg.get("apt", []))),
        "tests/test.sh": TEST_SH.format(seed=seed, answer=m.ANSWER_PATH),
    }
    common = (GEN / "common.py").read_text()
    gen = (GEN / f"{family}.py").read_text()
    solver = SOLUTIONS / f"{family}.py"
    for d in ("environment", "tests") + (() if solver.exists() else ("solution",)):
        files[f"{d}/common.py"] = common
        files[f"{d}/generate.py"] = gen
    if solver.exists():
        files["solution/solve.sh"] = SOLVE_FROM_WORKSPACE_SH
        files["solution/solve.py"] = solver.read_text()
    else:
        files["solution/solve.sh"] = SOLVE_SH.format(seed=seed, answer=m.ANSWER_PATH)
    return Path(out_root) / task_id, files, g


def all_tasks():
    return [(f, SEED) for f in FAMILIES]


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if committed task dirs are stale")
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args(argv)
    out_root = Path(args.out)
    stale, rejected, expected_dirs = [], [], set()
    for family, seed in all_tasks():
        out, files, g = build(family, seed, out_root=out_root)
        expected_dirs.add(out.name)
        if not g["admitted"]:
            rejected.append(f"{out.name}: {g['checks']}")
            continue
        for rel, text in files.items():
            path = out / rel
            if args.check:
                if not path.exists() or path.read_text() != text:
                    stale.append(str(path))
                    if path.exists():
                        sys.stdout.writelines(difflib.unified_diff(
                            path.read_text().splitlines(True), text.splitlines(True),
                            str(path), "expected", n=1))
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            if rel.endswith(".sh"):
                path.chmod(0o755)
        # A file the build no longer writes must not linger: a stale generator
        # left in solution/ would hand the answer key back to the oracle.
        leftovers = [q for q in out.rglob("*") if q.is_file() and str(q.relative_to(out)) not in files] \
            if out.exists() else []
        for q in leftovers:
            if args.check:
                stale.append(f"{q} (no longer built)")
            else:
                q.unlink()
        if not args.check:
            print(f"{out.name:28} units {g['units']:>3} | careful {g['single_agent_min']:>5} | "
                  f"floor {g['single_agent_floor_min']:>5} | delegated {g['delegated_min']:>4} min")
    extra = [d.name for d in out_root.iterdir() if d.is_dir() and d.name not in expected_dirs] \
        if out_root.exists() else []
    if extra and not args.check:
        for name in extra:
            shutil.rmtree(out_root / name)
    elif extra:
        stale += [f"{out_root / e} (not a current task)" for e in extra]
    if rejected:
        sys.exit("budget gate rejected:\n  " + "\n  ".join(rejected))
    if stale:
        sys.exit("stale task files (run `make longhorizon`):\n  " + "\n  ".join(stale))


if __name__ == "__main__":
    main()
